#ifndef	MISVR_VERSION_INCLUDED
#define MISVR_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define MISVR_VERSION_MAJOR	1
#define MISVR_VERSION_MINOR	0
#define MISVR_VERSION_PATCH	2
#define MISVR_VERSION_BETA	0
#define MISVR_VERSION_VERSTRING	MAKE_STR(MISVR_VERSION_MAJOR) "." MAKE_STR(MISVR_VERSION_MINOR) "." MAKE_STR(MISVR_VERSION_PATCH) "." MAKE_STR(MISVR_VERSION_BETA)

#endif
